# Site settings
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Dancy's open dev footsteps
url:                 http://swingseagull.github.io/
baseurl: 			 ""
encoding:			 utf-8
name: 				 Dancy Xia
avatar: 			 https://avatars.githubusercontent.com/u/5642994?v=3
description: 		 I am happy because I have dream
# Build settings
github_username:  swingseagull
#pygments/rouge 
highlighter: 		 pygments
markdown: kramdown
permalink: /:year/:month/:day/:title/

#pygments/rouge 
highlighter: 		 pygments
markdown: kramdown
permalink: /:title/

#footer-links
footer-links:
  linkedin: dancyxia
  github: swingseagull
  twitter: swingseagull1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dancy Xia
  url:               https://twitter.com/swingseagull1
  

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/swingseagull.github.io

#footer-links
footer-links:
  linkedin: dancyxia
  github: swingseagull
  twitter: swingseagull1
  
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md